package edu.up.br.exemplo.model;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class Endereco 
{
	/**
	 * 
CREATE TABLE Endereco (
	id_endereco INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	cep VARCHAR(8) NOT NULL,
	endereco VARCHAR(100) NOT NULL,
)

	INSERT INTO Endereco (cep, endereco)
	VALUES ( '12345678', 'Rua Sasasfrais')
	
	INSERT INTO Endereco (cep, endereco)
	VALUES ( '45678902', 'Rua Xuxu')
	
	INSERT INTO Endereco (cep, endereco)
	VALUES ( '56789033', 'Rua XPTO')
	 * @param cep
	 * @return
	 */
	public String buscar(String cep) 
	{
		String endereco = null;		
		if( cep != null && !cep.equals("") ) {
			ConnectionDB gerenciador = new ConnectionDB();
			Connection conexao = null;
			Statement editor = null;
			ResultSet conjResultados = null;
			try {
				conexao = gerenciador.connect();
				editor = conexao.createStatement();
				
				String comandoSQL = "select * from endereco "
						+ "where cep='"+cep+"'";
				
				conjResultados = editor.executeQuery( comandoSQL );
				if( conjResultados.next() ) {
					endereco = conjResultados.getString("endereco"); 
				}
			} catch (Exception e) {
				return null;
			} finally {
				try {
					conjResultados.close();
					editor.close();
					gerenciador.disconnect( conexao );
				} catch (Exception e2) {}
			}
		}
		return endereco;
	}
}
